### ISSUE TITLE
【宿題③】到達経路、127.0.0.1:8080:80 => コンテナ を明示する

### ISSUE THREAD

**Issue by maco1222** [GitEngHar/GrowTheLatestTechnorogy#15]
### 何でやるのか
- (http)127.0.0.1:8080:80 がコンテナに到達する経路を明示的にするため
  - Docker構成が現時点では漠然的なため、システム導入の際にしておく必要がある　  

### 何をやるのか
-  (http)127.0.0.1:8080:80 がコンテナに到達する経路を調べる。

### 理想の状態
-  (http)127.0.0.1:8080:80 がコンテナに到達する経路がわかる状態。

**Comment by GitEngHar** [comment]
### 何でやるのか

### 何をやるのか

### 理想の状態

**Comment by GitEngHar** [comment]
- 進め方
  - お願いマン(S)
    - ①このデータ欲しい
    - ②考察して①へ
  - 調査側（T）
    - ①そのデータを取る

次にのステージみたいなところに進むときに、共有ができればいい。
考察の段階でデータを整理して提案してくれると嬉しい

**Comment by GitEngHar** [comment]
1. 検証環境の準備
2. 到達経路の調査
3. 到達経路の構成図を簡単に作成する
4. 進捗報告用にまとめる

**Comment by GitEngHar** [comment]
2. 到達経路の調査

powershell、ubuntuからできる

- コンテナに対して疎通確認をしてみる

- ポート指定をしてみる

- その経路が表示されるコマンドで実施する
  - tracepath,traceroute

**Comment by maco1222** [comment]
### コンテナに対して疎通確認をしてみる
検証環境できたか確認
```
 PS C:\Users\MakoT> docker ps
CONTAINER ID   IMAGE     COMMAND              CREATED          STATUS          PORTS
  NAMES
dc06ef7c673f   httpd     "httpd-foreground"   39 seconds ago   Up 38 seconds   127.0.0.1:8080->80/tcp   clever_dewdney
```

コンテナのIPアドレスを調べる
```
PS C:\Users\MakoT> docker exec -it dc06ef7c673f /bin/sh
# ^C
# ls
bin  build  cgi-bin  conf  error  htdocs  icons  include  logs  modules
# hostname -i
172.17.0.2
```
pingで疎通確認できない
```
PS C:\Users\MakoT> ping 172.17.0.2

172.17.0.2 に ping を送信しています 32 バイトのデータ:
要求がタイムアウトしました。
```
Webページが開けない状態だと疎通結果はFalseになった
![image](https://user-images.githubusercontent.com/127610311/232264434-93dcf4e8-71e7-4690-a62a-59399c45482d.png)

webページ開いた状態
<img width="960" alt="image" src="https://user-images.githubusercontent.com/119464648/232264720-facfa659-7162-4307-95d0-75fd6e2e8eff.png">

**Comment by GitEngHar** [comment]
docker exec -it dc06ef7c673f /bin/sh

**Comment by GitEngHar** [comment]
> pingで疎通確認できない

おそらく、別コンテナからであれば疎通が通りそう。
通れば、Dockerレイヤで管理されているIPのため、Desktop上のPowershellなどはDockerレイヤではないため、別のアドレス必要がある

port指定する方法
`  Test-NetConnection 127.0.0.1 -port 8080  `
https://pasomaki.com/powershell-ping-port/

**Comment by maco1222** [comment]
```

PS C:\Users\MakoT> Test-NetConnection 127.0.0.1 -port 8080
警告: TCP connect to (127.0.0.1 : 8080) failed


ComputerName           : 127.0.0.1
RemoteAddress          : 127.0.0.1
RemotePort             : 8080
InterfaceAlias         : Loopback Pseudo-Interface 1
SourceAddress          : 127.0.0.1
PingSucceeded          : True
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False
```

**Comment by GitEngHar** [comment]
@maco1222 

一旦tracerouteで経路調べてほしいですmm

コマンドwindows環境から打てず下図のようにwindows上のubuntuで打つ必要がある感じです
<img width="637" alt="image" src="https://user-images.githubusercontent.com/119464648/232265652-9852b9f5-424d-4a6b-a725-97f1d59fca68.png">

以下ubuntuのセットアップ方法とtracerouteの設定方法を書きますね

【設定方法】
- [こちら](https://www.osarusystem.com/misc/windows11_wsl_ubuntu2204.html#:~:text=wsl%20%2D%2Dupdate-,Ubuntu%2022.04%20LTS%E3%81%AE%E5%B0%8E%E5%85%A5,-Microsoft%20Store%E3%82%92)からubuntnu環境をセットアップ
  - リンク先がページの途中かと思いますが、そこから進んでもらって大丈夫です
- tracerouteの設定は以下を参考にubuntu上で実行してください
```
### whichで該当のコマンドがinstallされていないことを確認。(何も返答がなければinstallされていない)
$ which traceroute

### installの実施(選択肢は全てyで大丈夫です)
### 各項目実行が完了次第次に進む(実行結果なくてごめんなさい)
$ sudo apt-get update

$ sudo apt-get upgrade

$ sudo apt-get install inetutils-traceroute

### install確認(同じ結果が帰ってくれば成功)
$ which traceroute
/usr/bin/traceroute

```

**Comment by GitEngHar** [comment]
@maco1222 
上記完了後に、tracerouteを使ってコンテナにポート指定して疎通が通るか確認してみてくだせぇ(`･ω･´)b

**Comment by maco1222** [comment]
#### コンテナのポート転送を確認
```
PS C:\Users\MakoT> docker container port wizardly_chebyshev
80/tcp -> 127.0.0.1:8080
```
#### コンテナの疎通経路をport指定して確認
```
root@tsunoda:~# traceroute --port=80
traceroute: missing host operand
```
ポートが見つからないと表示されてしまう...

#### コンテナの疎通経路をIPアドレスを指定して確認
```
root@tsunoda:~# traceroute 172.17.0.2
traceroute to 172.17.0.2 (172.17.0.2), 64 hops max
  1   172.25.96.1  0.190ms  0.094ms  0.076ms
  2   192.168.3.1  1.262ms  0.943ms  0.906ms
  3   *  *  *
  4   *  *  *
  5   *  *  *
  6   *  *  *
  7   *  *  *
  8   *  *  *
  9   * ^C
```
172.17.0.2にたどり着かない...

ubuntuのセットアップ完了/tracerouteインストールしたことを確認済み
![image](https://user-images.githubusercontent.com/127610311/232485403-227967b0-c842-4a4c-8136-f404b3d7e5fd.png)


ubuntuはdockerアプリ外のため、コンテナのIPアドレスではなくhttpのIPアドレスにて確認する
```
root@tsunoda:~# traceroute -p 8080 127.0.0.1
traceroute to 127.0.0.1 (127.0.0.1), 64 hops max
  1   127.0.0.1  0.002ms  0.001ms  0.001ms
```

**Comment by GitEngHar** [comment]
- tracerouteでコンテナから外部(例えばgoogle)の通信経路を見る
  - traceroute はデフォルトだとUDPの指定となるため正しい通信経路を見れないので注意 
- 通信経路の所在を調べる

分からなくなったら下を参考にしてみてくださいmm
https://github.com/GitEngHar/GrowTheLatestTechnorogy/issues/16#issuecomment-1518448288
